<h1>Lifestyle Considerations</h1>
<h3>Age</h3>
<p>People who are younger need a greater amount of sleep. This particularly affects those who are underage and have not fully matured yet, because they are still growing both mentally and physically. Extra SWS time is spent to boost bodily growth and extra REM time is spent to boost learning and memory retention. For people who are underage, the total amount of light sleep is much smaller and there is a higher percentage of REM and SWS in daily sleep totals; extra sleep in general is also likely to be beneficial. Consequently the total amount of daily sleep reduction that is possible for underage is very small and polyphasic sleep schedules which aim to significantly cut sleep totals should probably be avoided.
<h3>Exercise</h3>
<p>In general, activities which involve only light-to-moderate exercise (e.g. light cardio or light sports) should not have any significant impact on sleep architecture. However, activities that are very physically strenuous or which involve high-intensity exercise (e.g. heavy sports, weight lifting, HIIT, etc) should be taken with more consideration - when engaging with these activities, additional time is required for things such as muscle and tissue repair, and for this reason the daily SWS requirement is increased, with the increase in SWS usually causing a reduction in the total time spent in the LNREM2 sleep stage. Total time spent asleep has also been found to increase. Consequently, the total amount of daily sleep reduction that is possible for people who are engaging in these sorts of activities is reduced, because they need more sleep overall.</p>
<p>Due to low amounts of SWS during adaptation on schedules with extreme levels of sleep reduction, especially nap-only schedules which will encounter severe SWS rebounds during the adaptation period, some care should be taken not to engage in overexertion and extra time may have to be spent to recover even after light or moderate levels of exercise. After the adaptation period this effect should be less noticeable.</p>
<h3>Sickness</h3>
<p>During times of sickness, a significant increase in the amount of slow wave sleep results in a boost to the immune system which helps it to effectively fight off whatever is making you ill. Consequently, the total amount of daily sleep reduction that is possible for people who are sick or ill is very small. For this reason, it is strongly advised that whenever a polyphaser is sick, they switch to a schedule which would allow for a greater amount of SWS. Traditionally this would mean dropping back down to monophasic sleeping until the illness has been dealt with, or adding extra cycles in SWS-favourable times to the entrained schedule's existing sleep blocks.</p>
<h3>Caffeine</h3>
<p>Caffeine antagonizes adenosine receptors which can lead to reduced drowsiness. However, it also has some other effects, including increased heart rate, increased sleep latency and reduction in sleep quality. In general, caffeine has a half-life of around 6 hours and increased dosage leads to more significant effects.</p>
<p>The general consensus within the polyphasic sleeping community is to completely cut caffeine out of the diet. However, this is likely to lead to caffeine withdrawal symptoms for people who have built up a tolerance and dependence on caffeine, so if the plan is to remove caffeine from the diet it is probably a good idea to spend a few weeks without it (in order to get past withdrawal symptoms) before starting a polyphasic sleeping schedule.</p>
<p>It should be noted that Puredoxyk mentions in her Ubersleep book that she was given soda to stay awake during her initial Uberman adaptation, and has been known to drink coffee and other things while sleeping polyphasically, which would be in contrast to the general advice normally given. It might also be beneficial to use small doses of caffeine to offset sleep deprivation symptoms during an early period of adaptation or during the initial sleep deprivation period. Further research is required in this area.</p>
<h3>Alcohol</h3>
<p>It has been observed that alcohol consumption can increase depth and length of slow-wave sleep, and huge amounts (more than 1 or 2 drinks) can lead to REM reduction. Drinking significant amounts of alcohol also leads to significant sleep architecture disturbance, which can completely wreck a polyphasic adaptation. Consequently, it is probably not advisable to drink huge amounts of alcohol while polysleeping. It is also not really advisable to drink alcohol prior to any sleep sessions which are intended to be REM-focused. It might be okay to drink a small amount prior to sleep sessions which are focused on SWS without significant schedule damage, but large quantities are not advised and avoiding drink entirely is probably the safest option. Further research is required in this area.</p>
<h3>Modafinil</h3>
<p>Consumption of Modafinil while on polyphasic sleeping is not recommended due to extremely long half life (15 hours) which means it is likely to impact the quality of multiple successive sleep sessions. Further research is required in this area.</p>
<h3>Low carb / Keto diet</h3>
<p>It was suggested by some people in the polyphasic sleeping Discord that a ketogenic diet (low carbs, adequate protein, high fat) is helpful for poly sleep because consuming carbs increases tiredness and/or sleep need. So far no evidence presented to support this claim. Further research is required in this area.</p>
<h3>Eating time versus nap time</h3>
<p>It is generally suggested that it is better to eat just after waking up from sleep so that your body isn't having to digest food while sleeping. Indeed it can be very hard to sleep if your belly is overflowing. Contrastingly though I've also found that it's hard to sleep if your stomach is grumbling due to being hungry. Further research is required in this area.</p>
<h3>Room temperature when sleeping</h3>
<p>It has been suggested that room temperature has a notable impact on sleep quality. Further research is required in this area to determine how much impact there is and the most optimal temperature range to sleep in.</p>
<h3>REM sleep and depression</h3>
<p>There appears to be a link between REM sleep frequency/quantity and depression. In particular, reducing REM frequency and quantity appears to reduce severity of depression and SSRIs (common antidepressants) appear to function by reducing both REM quantity and also REM deprivation symptoms. Information along these lines has been supported by study. Consequently, polyphasic sleep might have the initial effect of dampening depressive symptoms, but after REM rebound they might be amplified. (This would support my observation where I was able to get so far into schedule without any depression at all and then suddenly I get a huge surge of it which kills the adaptation). Further research is required in this area.</p>
<h3>Meditation versus sleep</h3>
<p>Some people have claimed that meditation can be used instead of sleep to serve the same purpose. This sounds like complete crap to me but I'm not willing to dismiss this without evidence. Further research is required in this area.</p>
<h3>Masturbation, porn and sex</h3>
<p>Masturbation, porn and sex are likely to make you subsequently feel tired and want to sleep, so if you want to engage in these activities, it might be better to do them shortly before sleeping. Some people in the polyphasic sleeping community are also part of the NoFap community and don't masturbate at all; whether this is helpful or not is debatable. Further research is required in this area.</p>
<h3>Long-term metabolic effects</h3>
<p>It appears that even after successful adaptation there are likely to be long-term metabolic effects of polyphasic sleeping, especially on extreme schedules. There is plenty of evidence to support this and the consensus from veterans on extreme schedules seems to be that you get more hungry. A notable example of this phenomenon is aeia, who lived on Uberman between June 2009 and March 2010 and has a prominently notable video blog of the experience on YouTube. She eventually quit because she felt that she was gaining too much weight, and every single diet that she tried failed to stop the problem; eventually this impacted her modelling career and she was forced to pack in the schedule. It is also very plausible that eating could be an effective way to counter sleepiness which might otherwise occur from having low volumes of sleep. Further research is required in this area.</p>
<h3>Interspersing sleep with the waking world</h3>
<p>Some schedules require extremely strict adherence in order to maintain them long term, but it is generally very difficult to avoid real-life interferences to schedules. Real life examples of interferences I've experienced include:</p>
<ul>
<li>Someone walking in on me where I sleep at work and waking me up by accident because I forgot to lock the door</li>
<li>Someone intentionally waking me up to check I'm okay because why the hell am I sleeping at this odd time</li>
<li>Phone call from a nuisance caller in the middle of sleep</li>
<li>The house cleaner deciding to make a huge noise cleaning the house at exactly the time I'm trying to sleep and then leaving just as my sleep time ends</li>
<li>A housemate deciding to hold a very noisy impromptu party at my house without even checking with me, thus blocking me from sleeping</li>
<li>The ticket machine broke at the train station, and the guy at the kiosk trying to sell me a ticket instead sold me the wrong one and wasted ages trying to correct his mistake, causing me to miss the train I'd planned to catch that would have avoided having to sleep on the train. The ticket inspector on the train then woke me up during the sleep session in order to check my ticket</li>
<li>A power cut in the middle of the night making staying awake difficult due to sheer boredom</li>
<li>An internet outage in the middle of the night with the same result</li>
<li>Alarm failing to go off</li>
<li>Method used to turn alarm off being too simple</li>
<li>Pavlok (an electric shock wristband used as an alarm) stopped working properly (failing to receive zaps from the internet because phone went into doze mode, failing to transmit zaps from the app to the wristband because the bluetooth connection is shite and keeps unpairing, failing to zap because it was out of battery, random firmware error at 2am making it lock up and need a firmware reset)</li>
<li>Becoming immune to Pavlok so 100% zap doesn't wake me up</li>
<li>Lack of motivation to get out of bed for whatever reason</li>
<li>Depression</li>
</ul>
<p>Also, Maddy had her pets mess up her naps quite a few times, including one time where one of her dogs carried her phone away into some other room so she couldn't hear the alarm and consequently overslept.</p>
<p>There may also be some considerations for emergency circumstances occurring during a polyphasic sleep session. Given the increased sleep depth, entering slow wave sleep could prove devastating if there is some sort of emergency (e.g. a house fire, a burglarly, etc) which you would ordinarily wake up to deal with. It is plausible that you will not hear the alarm go off and therefore will fail to wake up. <a href="https://www.reddit.com/r/polyphasic/comments/5av0q6/sometimes_polyphasic_sleep_can_be_bad_like_this/">This has happened to generalNguyen in the past</a>, although fortunately it was a false alarm. Still, this should be taken into consideration.</p>
<h3>Daylight saving time</h3>
<p>In most parts of the world the clocks move forward in the spring and then backwards again in the autumn. This can interfere slightly with polyphasic scheduling. In general you should try to stick to all of your sleep times during the DST changeover, sleep blocks should be kept to the same length and sleep blocks which are near to or overlap the border might need to have their timings tweaked to alleviate excess sleep deprivation. Most polyphasers do not find this to be a considerable issue.</p>
<p>If the DST changeover is just after you start your schedule, you might want to start sleeping on the new timezone early in order to make sure the adaptation period keeps consistent scheduling.</p>