<h1>Introduction</h1>
<h3>What is polyphasic sleeping?</h3>
<p>Polyphasic sleeping is the practice of sleeping multiple times per day. It is in contrast to a normal 'monophasic' sleep schedule (sleeping once per day) which is currently the default sleep pattern practiced in the western world.</p>
<p>You might consider this to be a rather odd concept, but polyphasic sleeping is neither new nor strange. Many animals sleep polyphasically, as do newborn human babies and young children. In fact, for most of recorded history, even adults followed a polyphasic sleeping pattern, taking a 'first sleep' early in the evening, waking during the middle of the night for several hours and then returning for a 'second sleep' in the early hours of the morning. People would use the time between these two sleeps for activities such as prayer, writing, sex and dream interpretation. The industrial revolution and the introduction of electric lighting allowed people to stay up later, which eventually led to this practice falling out of favour and eventually being forgotten by most of the population.</p>
<h3>Why would someone want to sleep polyphasically?</h3>
<p>Polyphasic sleeping has a number of benefits in contrast to a normal monophasic sleep pattern. The primary touted benefits include:</p>
<ul>
<li><strong>Increased wake time:</strong> Sleeping polyphasically allows you to sleep for a shorter amount of time in total, giving you more waking hours per day. The most extreme polyphasic schedules can provide up to 22 waking hours per day, which grabs the attention of busy people who rarely get time to themselves. Being awake during the night allows you to engage in activities during times which you would otherwise be asleep, such as night-time strolls, international conference calls with other time zones or extra work shifts.</li>
<li><strong>Improved sleep quality:</strong> By sleeping in a polyphasic fashion, it is possible to raise overall sleep quality by placing sleep blocks during times which align with the rhythms of the body, prioritizing important phases of sleep over those of low importance, increasing sleep depth and increasing sleep compression.</li>
<li><strong>Power napping:</strong> Taking short power naps throughout the day can provide significant benefits for alertness, performance and creativity without making you feel sleepy.</li>
</ul>
<p>Many proponents of polyphasic sleep like to use these benefits to suggest that polyphasic sleep is 'better' and that 'everyone' should be polyphasic. I would personally consider this to be a flawed argument. Polyphasic sleeping also has its downsides and does not suit everyone's lifestyle. In particular the following downsides should be noted:</p>
<ul>
<li><strong>Difficult adaptation:</strong> Adapting to a polyphasic sleep pattern is very difficult and requires you to be sleep deprived for a long period of time (usually 3-5 weeks) until the body gets used to the new schedule and subsequently recovers. On the more extreme schedules (which amusingly seem to be more popular) the sleep deprivation is extremely intense and far beyond anything people have previously experienced. Most people who attempt polyphasic sleeping severely underestimate the difficulty of such a long and continuous period of intense sleep deprivation (even after being warned) and crash out of their adaptation before they give themselves enough chance to adapt.</li>
<li><strong>Rigid scheduling:</strong> Most polyphasic sleep schedules require you to sleep for fixed durations at fixed times. Deviating from your schedule can make you feel exhausted or destroy your adaptation altogether. This can be particularly inconvenient. Since most schedules contain at least one daytime nap, this also prevents you from being able to stay awake all day, which might not be preferable.</li>
<li><strong>Unconventional:</strong> The rest of the world is not polyphasic. Following this sort of sleep pattern can cause chaos with social interaction (e.g. you can't go for a night out, because you have to sleep) or with work shifts (e.g. because you have to sleep during the working day, which might interfere with the desires of your employer). It can also block you from attending events, meetings, etc. especially in situations which you have no control over the timing of.</li>
<li><strong>Restricted activity:</strong> Actions which would significantly increase sleep need or interfere with sleep sessions have to be avoided. For example, most polyphasic sleepers avoid drinking caffeine or alcohol because these substances can interfere with sleep. People on severely reduced sleep hours also have to avoid working out too hard as they have less sleep time available for muscle repair.</li>
<li><strong>Hard to sustain when sick:</strong> When you are sick or unwell you usually end up having to sleep extra in order to fight off the illness. While sleeping monophasically this is not really a problem, but if you are on a polyphasic sleep schedule the extra sleep can sometimes completely kill your adaptation, even if you have been adapted to it for a long time. This means you have to adapt all over again, which can be enormously difficult and inconvenient, especially if you have built your life around a polyphasic sleep schedule.</li>
</ul>
<p>This is not an exhaustive list of pros or cons, but it should put across to you that polyphasic sleep is not necessarily better than monophasic sleep. As with many facets of life, the decision to sleep polyphasically should be weighed up for its advantages and disadvantages. If, after weighing everything up, you think that sleeping in a polyphasic fashion might be for you, then and ONLY then should you proceed.</p>
<h3>I've chosen to try polyphasic sleep - what now?</h3>
<p>Before you begin sleeping polyphasically, here are the basic steps you should follow:</p>
<ul>
<li>Gather as much information about polyphasic sleep as possible</li>
<li>Figure out which schedules are suitable for you, and then which one of those you would prefer to try</li>
<li>Prepare yourself for the adaptation period as best as you can before starting</li>
</ul>
<p>In particular, gathering information is extremely important, particularly from reputable sources. Too many people try polyphasic sleep with a lack of accurate information and consequently have no idea what they are doing - this usually leads to failure. For this reason, I have put together this website is an attempt to give you the best understanding possible about polyphasic sleeping, and from here you can learn about pretty much everything you need to know to be successful with polyphasic sleep. If that doesn't serve your purposes for whatever reason, here are some other resources you can check out:</p>
<ul>
<li><strong>Polyphasic Sleep Discord:</strong> This is a public chat server operated by people who have a good amount of polyphasic sleeping experience. If this website does not answer your questions then I would recommend the Discord server to be the first place you visit. You can use it to ask for help and advice with your scheduling or just to discuss polyphasic sleep in general. You can also go there to personally ask me questions if you like (I have been part of the server staff since May 2017).</li>
<li><strong>Ubersleep: Nap-Based Sleep Schedules and the Polyphasic Lifestyle - Second Edition:</strong> This is a book written by Marie Staver (aka Puredoxyk) who is often reported to be the inventor of the Uberman and Everyman sleep schedules. It is an excellent resource for beginners. HOWEVER, please be warned that it is quite outdated, lacking a lot of modern understanding about polyphasic sleep which has surfaced in subsequent years, and in places it uses old schedule names that are no longer appropriate. It also tends to understate the sheer difficulty of the adaptation or how long it might realistically take (e.g. it claims Uberman can be adapted to in 1 week, which is an extremely unrealistic timescale), and along with prior articles by Puredoxyk has contributed to a lot of misinformation being spread around on the subject over the years. It nevertheless still stands as one of the best printed resources on this subject.</li>
<li><strong>Polyphasic Society:</strong> The website PolyphasicSociety.com is one of the few sources of information relating to polyphasic sleeping currently on the internet. It was once run by Forevernade, who authored a lot of the content there. Sadly, when he stopped being active in the community, the site ended up being taken over by some less-than-reputable individuals who, while leaving the apparently useful content on the site, have also loaded it with 'scammy marketing' such as trying to sell sleep mastery e-books. In addition, while much of the info on that website is known to be reliable, other parts are theoretical and experimental with very minimal proof for the validity of said info. The site presents the content in such a way that it's hard to tell the reliable and experimental data apart. Thus you should try to remain critical of the information that's presented there.</li>
<li><strong>/r/polyphasic:</strong> This is a subreddit dedicated to polyphasic sleeping. You should really go there only as a last resort, because it was mostly abandoned when the community moved to Discord. It also carries a lot of misinformation (although this is pretty normal for Reddit).</li>
<li><strong>Puredoxyk's slack:</strong> The author of Ubersleep operates a Slack server with a chat room. Currently, however, PD's slack is very quiet and doesn't have a very large number of active participants, so it does not tend to be very useful (although it's a good way to get in touch with PD if you want to do that). It also does not welcome underage participants, suffers from a number of freedom of speech issues (which is most likely why it's so quiet), and the people who frequent the group tend to be pretty dismissive of our efforts and guidance. Go figure.</li>
</ul>
<p>There are several other places to find information online and some are better than others. It is a real minefield out there. Consequently, you should be very critical about everything you read and hear on this subject. In particular, you should avoid places such as YouTube video blogs (many new polyphasic experimenters have a habit of making a video blog about how great it's going to be, only to fail horribly and then abandon the project). You should also avoid the website SuperMemo - the author of this website appears to hold a grudge against the polyphasic sleeping community and has taken it upon himself to try to debunk the theories behind polyphasic sleep by misconstruing facts and twisting evidence to support his claims (unfortunately managing to get his opinions spread as far as both Wikipedia and Google). Another often-mentioned information source is the blog of Steve Pavlina, who did the Uberman sleep schedule for just under 6 months in 2005-6; unfortunately, like with Puredoxyk's book, he seriously understates the adaptation timescale and his blog has led to a lot of overoptimistic experimenters over the years, so you should take what you read there with some healthy skepticism.</p>
<p>There is also a new website coming soon which will look at polyphasic sleep from a more scentific viewpoint, but for now that site is still under construction and isn't available.</p>
<p>If anyone else wants to suggest some good information sources to list here, please poke me and I'll add them.</p>