<h1>Sleep Mechanics</h1>
<h3>Stages</h3>
<p>While sleeping, humans pass through 4 different stages of sleep in a cyclical fashion. The stage most people will be familiar with is Rapid Eye Movement (REM); the other three stages are known as Non-REM (NREM) and are numbered 1 through 3.</p>
<p>The general purpose of each stage is as follows:</p>
<h4>NREM1 and NREM2, aka "light sleep"</h4>
<p>These are very light stages of sleep which act as a buffer to cushion between other sleep stages. They also appear to act as a general purpose wakefulness sustainer. Some people call these stages LNREM ("light non-REM sleep") so you may see them referred to as LNREM1/LNREM2 or shortened to L1/L2. (The latter will be regularly used within this website for the sake of brevity.)</p>
<p>It is possible these sleep stages serve other functions besides acting as a buffer and wakefulness sustainer, but this hasn't been conclusively proven. Consequently, they currently appear to have no essential or critical purpose.</p>
<p>L2 is deeper than L1, but both of these sleep stages are still very light and easy to wake from. People who are woken from the L1 sleep stage are usually not aware that they were even sleeping and believe themselves to have been awake for the entire time.</p>
<h4>NREM3, aka "slow wave sleep" or "deep sleep"</h4>
<p>This stage of sleep, commonly shortened to SWS, is a multi-purpose sleep stage which performs many functions. It is known to be responsible for healing muscles, repairing tissue damage, boosting immune system function, regulating synapses, preservation and consolidation of declarative memories, and restoration of glial cells which provide energy to the brain.</p>
<p>SWS is an extremely deep type of sleep which is hard to wake from. While someone is in this stage of sleep, brain activity slows to ~75% of normal, which results in grogginess and considerable sleep inertia if someone is awakened during this stage, since it takes the cerebral cortex time to resume its normal functions.</p>
<p>In the past, this sleep stage was separated into two different stages (NREM3 and NREM4). They have only been treated as a single sleep stage since 2007. Consequently, some older texts may still reference there being four NREM stages.</p>
<h4>Rapid eye movement (REM)</h4>
<p>This stage of sleep is the most widely-known stage and is responsible for preservation and consolidation of procedural, spatial and emotional memories. It is also known to provide a boost to creativity - after waking from this stage people have been seen to perform better on problem solving tasks.</p>
<p>About 80% of dreaming occurs during REM. While this happens, the muscles become paralyzed and the eyes move very rapidly, which is where the name REM comes from.</p>
<h3>Cycles</h3>
<p>During a normal night of sleep, the body switches between the four stages of sleep in 'cycles'. Each cycle lasts just over 90 minutes on average, although the cycle length for each human varies depending on circumstances and the activities of the previous day, and might be anywhere between 60-120 minutes in length. If allowed to wake naturally, a normal human engaging in monophasic sleep will usually sleep for a total of 5 sleep cycles, giving just under 8 hours of sleep in total.</p>
<p>Prior to the start of the first sleep cycle, there is a short period of L1 sleep. The general structure of a sleep cycle then proceeds as follows:</p>
<p>L2 - SWS - L2 - REM - L2</p>
<p>For a standard 5-cycle monophasic sleep session, the stages will therefore look as follows:</p>
<p>WAKE - L1 -  L2 - SWS - L2 - REM - L2|L2 - SWS - L2 - REM - L2|L2 - SWS - L2 - REM - L2|L2 - SWS - L2 - REM - L2|L2 - SWS - L2 - REM - L2 - WAKE</p>
<p>As you can see, the body essentially alternates between SWS and REM, using L2 sleep to cushion between these two stages. The SWS stage may also be observed as a series of SWS bursts positioned inside a block of L2, which can result in blocks of SWS appearing separated when performing sleep analysis.</p>
<p>The timings within a standard sleep cycle tend to follow a typical pattern. The first 25-27 minutes are usually made up of light sleep, after which the SWS stage normally begins; the REM stage follows some time afterwards. The daily totals for each sleep type are also fairly consistent, with the approximate total time spent in each stage in an 8 hour mono sleep being as follows:</p>
<p>L1 + L2 ~ 50-60% &nbsp;(around 4-5 hrs)<br>SWS ~ 20-25% &nbsp;(around 90-120 mins)<br>REM ~ 20-25% &nbsp;(around 90-120 mins)</p>
<p>It has been seen in some cases that REM and SWS totals could be even as high as 150 mins each (2.5 hrs) in situations where more than average is required. Some people also have different baseline requirements to others. For people with higher REM and SWS totals, the total sleep time and cycle length may be longer than normal, and/or the total amount of L2 may be reduced.</p>
<h3>Circadian and Ultradian Rhythms</h3>
<p>During the day there are two different rhythms responsible for regulating sleep:</p>
<h4>Circadian Rhythm</h4>
<p>This is a rhythm which repeats roughly every 24 hours, although in some humans the length can differ slightly. The circadian rhythm aligns the body to the time of day and is self-adjusting, making use of external environmental cues such as light and temperature in order to align itself properly.</p>
<p>The circadian rhythm affects peak times for REM and SWS gain. The peak time for SWS is just before dusk and the peak time for REM is roughly 9 hours later. The general result of this is that when you engage in monophasic sleep at night, each sleep cycle is NOT equal. Instead, in each subsequent cycle, the REM quantity typically increases and the SWS quantity decreases. Early cycles may have almost no REM and later cycles may have little to no SWS as the body positions the SWS and REM in the times that it considers most favourable. If the sleep session is well timed, and the need for SWS is not significantly raised in any way, the vast majority of SWS (if not all of it) is typically consolidated within the first two sleep cycles, leaving the remainder to be REM-focused.</p>
<p>It is possible to adjust and offset the circadian rhythm by use of external cues. In modern times, it is often pushed later than normal due to the introduction of high levels of blue light coming from artificial light sources such as bulbs, phones and computer screens. This means that people who always stay up late at night on their computers or phones may end up with an artificially delayed circadian rhythm which moves their favourable SWS and REM points later into the night, which can consequently make it difficult to get a good night's sleep. The effect can be partly countered by making use of blue light filters (covered further in the adaptation section of this guide).</p>
<h4>Ultradian Rhythm</h4>
<p>Also known as the basic rest-activity cycle (BRAC), this rhythm repeats roughly every 90-120 mins. At the start of each BRAC the brain is focused and alert. In the latter half the brain will slow down, leading to the last 20 mins or so of each BRAC where the brain functions the slowest and feels most tired.</p>
<p>Sleep cycles appear to be a manifestation of the ultradian rhythm which expresses itself while sleeping.</p>
<p><strong>Area of further research:</strong> Need to investigate relation between BRAC and sleep cycle length.</p>
<h3>Sleep Pressure and Rebounds</h3>
<p>The body can only survive without SWS and REM sleep for a limited amount of time. After this time has passed, a pressure point is reached whereby the body badly craves the sleep that it has missed out on. SWS and REM have different pressure points, and once these 'pressure points' are hit, the sleep deprived person will experience very severe sleep deprivation symptoms as the body tries to force it to rest; it will also give up with its normal sleep cycle structure and switch to a sort of 'emergency mode' where it will engage in the type of sleep it craves almost immediately next time you fall asleep. This catch-up sleep session is typically deeper than usual, with a higher level of sleep efficiency than would normally occur. This emergency feature of the body is known within the polyphasic community as a 'rebound' (and usually named based on the type of sleep that the body is catching up with, i.e. either 'SWS rebound' or 'REM rebound').</p>
<p>In the event that someone is getting some of a specific sleep type, but not enough to fully meet their daily requirements, sleep deprivation builds more slowly; rebounds will still eventually be observed, but there is a longer delay before they hit. Because SWS is normally before REM in each sleep cycle and is subsequently prioritized for recovery first, sleep reduction almost always results in REM sleep being cut from the schedule, leading to REM deprivation, which subsequently causes the REM rebound effect to be observed. It also means that SWS rebounds typically occur only on schedules with very low amounts of sleep where there is often inadequate time to allow for both SWS and REM and where the REM rebound takes time away from SWS acquisition.</p>
<p>The fact that the body has this 'emergency mode' available (whereby it jumps very quickly into a specific sleep type rather than following a normal cycle structure, and where that sleep is deeper and more efficient than usual) is extremely interesting and demonstrates the alternating pattern of SWS and REM is not the only method of sleep that the body has at its disposal - the body seems to be flexibile with regards to its sleeping arrangements and is able to adapt to its circumstances in order to survive.</p>
<p><em>(For an example of rebound behaviour, consider a typical Uberman adaptation attempt. This schedule has 2 hours of sleep per day spread across 6 short naps, and contains no long sleep blocks. To begin with, the naps prioritize LNREM1, LNREM2 and SWS sleep types first, and not REM sleep. Because of this, REM deprivation symptoms occur very early on and the REM pressure point is reached first, usually on around days 3-5, resulting in REM rebound. This makes all the naps feel great to wake from, but leaves very little room for SWS. Consequently, SWS deprivation builds over the next several days, eventually resulting in a subsequent SWS rebound on around day 7 or 8 which usually kills or ruins the attempt at adapting to this schedule.)</em></p>
<p>Interestingly, there does not seem to be any LNREM rebound, or at least one has not been observed. After a session of sleep deprivation, the body compensates by prioritizing REM and SWS and does not seem to care much about LNREM. (In one study there was a total regain of only 7% LNREM versus 68% SWS and 53% REM regained). This would seem to support the belief that the lighter stages of sleep have no critical or essential purpose.</p>
<p>Once the rebound recovery is over, the body switches back to its normal cyclical sleep pattern of alternating SWS and REM blocks buffered by LNREM2. This typically happens after around 25 minutes, with the SWS stage beginning very quickly. For this reason, a sleep session which begins with a REM rebound shares an interesting parallel with a typical first sleep cycle - in both cases, the SWS sleep phase begins at roughly 25 minutes into the sleep session.</p>
<h3>Cycle Depth and Compression</h3>
<p>The depth of each sleep cycle seems to vary. In particular, due to sleep pressure, the first sleep cycle of a sleep session is likely to be the deepest, as this is generally the time when the need for sleep is most urgent and when REM or SWS rebound is likely to occur. Consequently, when aiming to reduce total time asleep and raise overall sleep efficiency, it may be beneficial to avoid sleep sessions which consist of multiple cycles.</p>
<p>Keeping a consistently reduced level of sleep, especially in schedules with short cores under 3 hours in length, seems to lead to sleep cycle compression, a phenomenon whereby the length of the average sleep cycle ends up being reduced, sometimes by a significant amount, and where the shorter cycle length subsequently becomes standard behaviour. These compressed sleep cycles on average are more efficient than normal, with a higher level of sleep depth. Compressing the cycle to less than 60 minutes in length appears to be possible given sufficient sleep reduction.</p>
<p>The changes to cycle compression appear to be a temporary effect of reducing total sleep time, and do not seem to be learnable. Increasing total sleep leads to these changes being reversed (sleep depth is reduced and cycle length extends again). More significant total sleep increase results in greater reversion of these changes and a major increase in total sleep can lead to changes in these areas being fully undone.</p>
<h3>Minimum Sleep Threshold</h3>
<p>Due to the high importance of the SWS and REM sleep stages, it would be preferable not to reduce the total amount of time spent in these stages. This leads to the 'minimum sleep threshold', which is equal to the total combined amount of time typically spent in SWS, REM and unavoidable light sleep. For most people, this time is somewhere in the period of 3-4 hours. For example, if your average daily SWS and REM totals add together to be around 3.5 hours, your minimum sleep threshold will be slightly higher than that (probably around 3.7 hours or so once unavoidable light sleep is taken into account).</p>
<p>Schedules which have sleep time totals below the minimum sleep threshold tend to have a very high adaptation difficulty and a very low success rate (although amusingly, due to the significant sleep time reduction being seen as valuable, they also tend to have a certain 'wow' factor about them, which leads to a very high attempt rate). In order to pull off these schedules, a very high level of cycle depth and compression must be achieved, which is very difficult to do. It is plausible that these schedules are not healthy or sustainable in the long term, and that even with the high levels of cycle compression, mental or physical performance might be impacted in some level that is not subjectively noticeable. Oversleeping on these schedules is also even more detrimental than normal, as this very high level of sleep cycle compression is very easily reversed. Whether it is possible to truly fully adapt to these schedules is debatable.</p>
<h3>Interrupted Sleep</h3>
<p>If you place two different sessions of sleep too close together, the body fails to distinguish that they are separate, instead treating them as a single session that was interrupted. This can have a range of consequences, including high levels of drowsiness, lower sleep depth and difficulty with sleep scheduling.</p>
<p>The normal practice is to leave at least 2 hours of waking time between sleep sessions in order to ensure the body identifies them separately, which is often quoted as 1 BRAC. However, the exact length of time required to distinguish sleep sessions as separate seems to be dependent on individual factors, so 2 hours may not be enough time for everybody.</p>
<h3>Wake Time Programming</h3>
<p>The body appears to have a mechanism to learn wake times. After consistently sticking to certain wake times, light sleep starts to be seen at roughly that time, regardless of where in the sleep cycle you may be at that point. Since light sleep is easier to wake from, this makes it easier to get up and out of bed. This phenomenon can be observed regardless of which sleep stage you would otherwise be in at that time. If the wake time has been kept consistent enough, you may also find that you start to wake up naturally without needing to use an alarm clock.</p>
<h3>Wake Time Reduction</h3>
<p>When total sleep quantity is reduced, the amount of time that the body can stay awake without needing to sleep again is also subsequently reduced. While an 8 hour monophasic sleep session seems to allow someone to stay awake all day, people on reduced sleep schedules do not have this luxury and cannot stay awake as long. This effect is most likely because LNREM2 acts as a wakefulness sustainer; when reducing total sleep time and engaging in rebounds from high sleep pressure, LNREM2 is not favoured for recovery, and so this effect is largely lost.</p>
<p>A short nap lasting ~20mins seems to have roughly the same effect as a full ~90mins sleep cycle in terms of restoring wakefulness/alertness and providing a boost to stay awake, but this only seems to apply after a sufficient amount of sleep deprivation. It is plausible that this effect is boosted by placing sleep blocks in times that align well with the circadian and ultradian rhythms. It is also plausible that this effect is boosted by the increase in sleep depth caused by high levels of sleep pressure and high levels of sleep cycle compression.</p>
<h3>Statistically Likely REM</h3>
<p>Polyphasic Society claimed their sleep recordings showed high amounts of REM being statistically likely between the 3-3.5hr mark and the 4.5-5hr mark. For this reason it might be a good idea to extend 2-cycle or 3-cycle sleep sessions by up to 30 minutes in order to give extra REM sleep, and some schedules in their traditional format make use of this phenomenon in order to attempt to allow for higher REM sleep gains.</p>
<p>It should be noted that at the moment I have not done any research to specifically accept or dismiss this claim, and that most of the recordings taken by Polyphasic Society were done using Zeo which is known to sometimes misdetect LNREM2 as REM sleep. However, if the first two sleep cycles are placed in an SWS-favourable time period, most if not all of the SWS should be kept within the first 2 cycles, so the extension is probably safe anyway, regardless of whether or not it will give extra REM.</p>
<h3>Second Wind</h3>
<p>Second wind, also known as the sleep maintenance zone, is a phenomenon whereby after being awake for a long period of time, you will suddenly find yourself to be much less drowsy for a short period of time, usually between 2 and 3 hours. You may even find it very difficult to fall asleep, regardless of how tired you actually are. This phenomenon is caused by the body entering a wake-favourable circadian phase, triggering the production of cortisol, an adrenaline activator. It is plausible that the second wind has evolved as a survival mechanism to allow sleep-deprived people to briefly function at a higher level.</p>
<h3>Dream Memory Retention</h3>
<p>Waking up during/after a session of slow wave sleep does not seem to favour dream memory retention. Consequently, if you are designing a schedule where dream retention is preferable, this should be avoided.</p>