<h1>Dual Core</h1>
<p>The dual core family of sleep schedules was originally invented by the Polyphasic Society and is modelled around a similar concept to Segmented sleep. Instead of having a single long core, the core sleep is broken into two halves, with the first half being focused on SWS and the second half being focused on REM. A number of 20-minute naps are then added to round out the schedules and provide the remaining REM sleep needed.</p>
<p>These schedules are typically more difficult to adapt to than Everyman, because on average they contain shorter cores and the core gap must be tolerated during adaptation in addition to attempting to hit sleep rebound in the naps. They are also less well known, and consequently less popular than the Everyman schedules. However, the increased sleep quality offered by segmenting the cores into the SWS and REM peaks allows for further sleep time reduction.</p>
<p>Like with Everyman schedules, each variant of Dual Core is numbered based on how many naps it contains. So, for example, a Dual Core schedule containing 2 naps is consequently called "Dual Core 2", abbreviated to just DC2.</p>
<hr/>
<h2>Dual Core 1 (5 hrs 10 mins)</h2>
<p><a href="https://napchart.com/ugn4g"><img src="https://ncimg.tinytimrob.com/ugn4g" height=300 /></a></p>
<p><strong>Adaptation difficulty:</strong> MODERATE</p>
<p>This is the first Dual Core schedule, and follows logically from Segmented sleep. The extended cycle length from Segmented is retained, although shortened a little down to around 100 minutes per cycle, and like with Segmented the first core also gets extra sleep time to cover the statistically likely REM period. The second core is reduced to a single cycle in length, because the second cycle of that core from Segmented is replaced with a nap.</p>
<p>In general, while this schedule has the same total sleep time as Everyman 2, the adaptation is considered slightly harder.</p>
<p>Ideal scheduling is to place the first core at around 9.30pm, the second core at around 6am and the nap at around 2pm. If modification is needed, the core gap could potentially be shortened a bit, but this risks moving the sleep blocks further out of the favourable REM and SWS timings. Rotating this schedule is also very challenging for the same reason. If the schedule does get rotated, the entire circadian rhythm might have to shift around to compensate for the delay.</p>
<hr/>
<h2>Dual Core 2 (4 hrs 40 mins)</h2>
<p><a href="https://napchart.com/rxpjl"><img src="https://ncimg.tinytimrob.com/rxpjl" height=300 /></a></p>
<p><strong>Adaptation difficulty:</strong> SOMEWHAT HARD</p>
<p>This schedule follows from Dual Core 1, but with a further sleep time reduction. The target on this schedule is to reach a small cycle length reduction by compressing the sleep cycles down to 80 minutes, which is reflected in the shorter core times (160 mins and 80 mins respectively), and which is supported during adaptation by the fact that very short cores and lower total sleep time are likely to result in sleep cycle compression. The longer core is not significantly cut down here, so the compression that can be achieved is quite small.</p>
<p>An extra nap is added to compensate for the hour of sleep removed from the cores, because these shorter cores no longer cover the statistically likely REM period, so that extra REM must come from a nap instead. The total number of equivalent cycles of rest on this schedule is therefore back up to 5.</p>
<p>Ideal scheduling is to place the first core at around 10pm, the second core at around 6am and the naps at around 12pm and 4pm. As with Dual Core 1, modifying and rotating the schedule is quite challenging and the schedule suffers from the same sort of limitations in this area.</p>
<hr/>
<h2>Dual Core 3 (4 hrs)</h2>
<p><a href="https://napchart.com/arx4r"><img src="https://ncimg.tinytimrob.com/arx4r" height=300 /></a></p>
<p><strong>Adaptation difficulty:</strong> HARD</p>
<p>This is the shortest dual core schedule and the most difficult one to pull off. The 4 hour sleep total is on the border of the minimum sleep threshold for some people who might find the adaptation even more challenging, and the two short single-cycle cores can result in the sleep cycle being compressed down to anywhere as short as 60 minutes. This would make the cores 1.5 cycles long. The first core will account around 65% of the daily SWS and the high level of cycle compression could result in SWS wakes from that core during adaptation, making it even harder to stay awake during the graveyard hours. The second core will have a more balanced amount of SWS/REM, with marginally more REM, and is consequently most likely to have REM or LNREM wakes. Waking early from the second core is also possible, as the truncated second cycle of the first core might initially get treated as interrupted and bleed over into the second one. The three naps add up to complete the remainder of the daily REM total.</p>
<p>Ideal scheduling is to place the first core at around 10pm, the second core at around 2.30am, and then to place REM-targeted naps at around 7am, 12am and 4.30pm. Unlike with previous dual core schedules, the second core here is intended as a mixed core and can be placed further away from the REM peak because the remaining REM will be covered by the three naps.</p>
<hr/>
<h2>Dual Core 4 (4 hrs 20 mins)</h2>
<p>This schedule is considered an Uberman transitional schedule and is covered on the Uberman scheduling page.</p>