<h1>Dymaxion (2 hrs)</h1>
<p><a href="https://napchart.com/zgqtz"><img src="https://ncimg.tinytimrob.com/zgqtz" height=300 /></a></p>
<p><strong>Adaptation difficulty:</strong> INSANELY HARD</p>
<p><strong>Also known as:</strong> Dymaxion 4 or D4</p>
<p>The Dymaxion sleep schedule is probably the second most well-known nap-only sleep schedule. It consists of four equidistant 30 minute naps (one nap every 6 hours) and NO cores, giving a total of 2 hours of sleep per day.</p>
<p>The schedule itself was invented by Buckminster Fuller in the 1930s, who reportedly slept on this schedule for most of 1932 and 1933. The name stands for 'dynamic maximum tension' and was applied to many of Buckminster Fuller's other inventions from the time period including a house, a car and a map.</p>
<h2>Dymaxion vs Uberman</h2>
<p>Almost everything which applies to Uberman also applies here. As a nap-only schedule with a 2 hour sleep total, Dymaxion has great similarity with Uberman, including the extremely low success rate, insanely high difficulty, incredibly tough adaptation and virtually non-existant flexibility. And, like with Uberman, all of the SWS and REM must come from naps on this schedule, and the sleep compression is very high. However, it tends to be less popular, with less hype behind the schedule.</p>
<p>On the difficulty scale, it tends to be considered even harder than Uberman. The time between naps, being 5h30 instead of 3h40, can certainly be harder to sustain wakefulness for during the earlier part of adaptation. But the differing nap length is probably what makes this schedule more challenging even than Uberman.</p>
<p>As previously explained in this guide, the SWS sleep stage will begin at around the 25 minute mark when the need is high but the pressure is low, even with no sleep compression. Consequently this is exactly what happens - after the first day or two, every nap ends in SWS without any effort, because the nap is long enough to pass this SWS boundary. In contrast, with a 20 minute nap-only schedule like Uberman, you have to wait either for SWS pressure to hit a peak or for the sleep cycle to compress enough that the naps are able to get SWS, so you get none at all to start with.</p>
<p>The naps on Dymaxion subsequently end up being harder to wake from than those in the early days of Uberman, because they ALL end in SWS from the beginning, which results in groggy wake up from every nap until the body gets used to the nap length and performs wake time programming. Due to the constant SWS wakes, hearing alarms is even more difficult than on Uberman, with even less likelyhood that willpower will work as a method of getting you out of bed. The fact that every nap has some small amount of SWS also results in a significant delay to the arrival of the SWS rebound, which delays the adaptation process. On top of this, the SWS-ending naps have the disadvantage of significantly reduced chance of dream memory retention, and do not feel very euphoric upon waking. I've previously heard the naps during the early stages of a Dymaxion adaptation being described as 'like dying'.</p>
<p>Nevertheless, some people seem to prefer this schedule compared to Uberman. It certainly allows for much greater time awake between naps, which can be appealing.</p>
<h2>Adaptation</h2>
<p>The same rules apply to Dymaxion adaptations as to Uberman ones. And likewise, without a human supervisor, you basically stand no chance at all of adapting to the schedule.</p>
<h3>Gradual adaptation</h3>
<p>Here are some possible transitional schedules you could try if you want to take a stab at a gradual adaptation:</p>
<h4>Bimaxion (4 hrs) and Trimaxion (3 hrs)</h4>
<p><a href="https://napchart.com/qamnm"><img src="https://ncimg.tinytimrob.com/qamnm" height=300 /></a> <a href="https://napchart.com/awkwb"><img src="https://ncimg.tinytimrob.com/awkwb" height=300 /></a></p>
<p><strong>Adaptation difficulty:</strong> HARD (Bimaxion) / VERY HARD (Trimaxion)</p>
<p>These experimental '-maxion' transitional schedules follow a similar concept to those for Uberman. This essentially results in Dymaxion-style schedules where either 1 or 2 naps end up being replaced with cores. The transition approach is similar (usually Bimaxion -> Trimaxion -> Dymaxion) and suffers from the same issues as Uberman's transitional schedules.</p>
<p>In a weird choice of naming, the Bimaxion schedule used to be known as Quadphasic, which was a super dumb name. Fortunately it's not called that any more.</p>