<h1>Uberman (2 hrs)</h1>
<p><a href="https://napchart.com/omr2x"><img src="https://ncimg.tinytimrob.com/omr2x" height=300 /></a></p>
<p><strong>Adaptation difficulty:</strong> INSANELY HARD</p>
<p><strong>Also known as:</strong> Uberman 6 or U6</p>
<p>The Uberman sleep schedule is the most well-known nap-only polyphasic sleep schedule. It consists of six equidistant 20 minute naps (one nap every 4 hours) and NO cores, giving a total of 2 hours of sleep per day.</p>
<p>The basic concept behind Uberman, as well as its name, is the work of Marie Staver (Puredoxyk) and Psuke Bariah, who came up with the schedule in 1999 after reading an artice on Dymaxion sleep in TIME magazine. It was subsequently revealed to the world in a blog post on Everything2 in December 2000.</p>
<p>Uberman is the most famous form of non-biphasic polyphasic sleeping, as well as one of the most popular for beginners to try, most likely due to the huge amount of extra free time it provides. It could even plausibly be considered the icon of the whole polyphasic sleeping concept, as many people are intrigued by its unique nature. Since its inception, it has been attempted by an increasingly large number of wannabe polyphasers and the schedule itself has an enormous amount of hype. Unfortunately, it is also one of the most difficult schedules of all to succeed with. Due to the insane difficulty of this schedule, almost everyone who tries Uberman drops out before they complete the adaptation process - less than 1% of people are typically successful. It should also be pointed out that <strong>nobody has ever successfully adapted to this schedule without a human alarm clock</strong> (or at least I don't know of anybody who did) and that attempting to adapt to it without a partner to supervise and wake you will <strong>almost definitely result in failure</strong>.</p>
<p>Despite the high difficulty and extremely low success rate, this does not usually stop people from being initially overconfident about their adaptation chances. The initial information source for most beginners tends to be Puredoxyk or the blogs of Steve Pavlina, both of whom have severely understated how difficult the schedule is, along with significantly understating the length of the adaptation period. (The usual claim is that it takes around 1 week to adapt, whereas in reality the adaptation takes anything up to 6 weeks and the schedule doesn't begin to feel good for most until week 4.) Sadly, many wannabe Ubermen read these information sources and decide they will be able to tolerate 1 week of sleep dep and succeed. They subsequently create things such as blogs or YouTube channels where they explain how great the schedule will be, only to then fail within the first 10 days. Following on from this failure, they usually go on to make absurd claims like "polyphasic sleep doesn't work" and give up on polyphasic sleeping completely. These sort of botched Uberman attempts really do not do either the Uberman schedule or polyphasic sleeping itself much justice. While it is easy to find a successful adaptation log (as those get most attention and thus float to the top of Google/Youtube/Reddit), there are many more logs that get written for some small number of days and then the author suddenly disappears, presumably because they failed the adaptation and gave up. This is reflected by the number of people who attempted nap-only schedules such as Uberman in the past several months on the Discord server, only to fail horribly. It is therefore very important <strong>not to be fooled</strong> by any overzealous estimations or claims of success - the list of people who have been successful with this schedule could probably be written down without even filling one A4 page.</p>
<p>While providing a substantial amount of extra wake time, it is often hard to schedule any kind of appointments on this schedule, because there is absolutely no scheduling flexibility at all. The naps are equidistant, taken 20 minutes every 4 hours, and it is virtually impossible to move the naps around. This can cause scheduling headaches for social events, and makes the schedule difficult to align with lectures (for university students) or with paid employment (for adults). This in turn greatly reduces the number of people who are able to pursue this schedule due to time and social constraints, making it mainly applicable to people who are self-employed or who mostly study and work from home.</p>
<p>With the extreme sleep reduction and lack of research, it is very hard to assess the long term impact of this schedule on physiology and health. While no adverse effects have been reported so far, this is something that must be taken under consideration.</p>
<h2>Mechanics</h2>
<p>Like all nap-only schedules, both the SWS and REM needs on this schedule must come entirely from naps. The lack of cores and low total sleep time on this schedule will lead to very high levels of sleep compression, reducing the cycle length down to 60 minutes or maybe even less (it is hard to measure exactly, since there are no full cycles on the schedule to record the length of). After adaptation, the time required to fall asleep will typically be under 1 minute and the total amount of light sleep in naps will be no more than a few minutes. This leads to around 1h50 of non-light sleep per day, split as needed between SWS and REM.</p>
<p>While living on this schedule, the sleeper must maintain a very finely balanced equilibrium between SWS and REM pressure which works almost like a see-saw. Over the course of a waking block, the REM and SWS pressures slowly increase until they are too high, after which point the user must take a nap in order to drop the pressure back down to manageable levels. During the course of the nap, the sleep type with the highest pressure is recovered through an almost-immediate sleep rebound, causing the pressure of that sleep type to drop. This tips the scales in the favour of the opposite sleep type, which then takes focus immediately afterwards. With recovery of both sleep types, the pressure levels will drop almost back into balance. Sleep therefore essentially ends up in a constant flip-flop between REM and SWS as the body enters non-stop emergency mode in every nap to try and alleviate the sleep pressure. Consequently, mixed naps are very likely, and could be either REM-SWS or SWS-REM in order, with each nap on the schedule looking almost like a miniature sleep cycle.</p>
<p>Because of the reliance on high sleep pressure to maintain the schedule, circadian rhythm is not massively relevant or influential. It is possible to have SWS-heavy naps in the middle of the REM peak, or REM-heavy naps in the middle of the SWS peak, purely because the sleep pressure is so high. After adapting, the body will naturally wake itself at the end of each nap once the pressure has dropped to a low enough level, although maintaining alarms is still required as the pressure level between naps varies and natural wakes are not guaranteed.</p>
<h2>Sustainability</h2>
<p>So far, nobody has managed to live on this schedule sustainably and make it their permanent lifestyle scheduling choice. This is unlikely to change any time soon.</p>
<p>Given how heavily this schedule relies on sleep compression and high levels of sleep pressure to work, any form of oversleep or screwup is extremely detrimental to the adaptation - sleeping too much or for too long will reverse the cycle compression and lower the sleep pressure, which can completely crash you out of the schedule. In the past, it has been observed for people to crash out after just one extended sleep session, even after months or even several years on the schedule, and for this reason it is entirely questionable as to whether it is possible to ever be fully adapted to the Uberman schedule or whether you are simply sustaining a non-stop limbo state while living on it.</p>
<p>Doing heavy exercise or bodybuilding on Uberman is also not realistically possible. These activities will give a significant increase to SWS pressure which can totally destroy the schedule. Even if that can be managed, the very low amount of SWS on this schedule and the almost non-existant margin available for recovery can result in these activities having an extremely long recovery time which can leave you feeling physically exhausted.</p>
<p>Similarly, in the event of sickness, the schedule will almost certainly have to be dropped, because there is no extra SWS time available to boost the immune system in order to fight off the sickness, and the need for such time is likely to throw the sleep pressure out of balance and destroy the schedule anyway.</p>
<h2>Adapting to Uberman</h2>
<p>Uberman adaptation is one of the hardest, and many people try to promote or even sell you their 'awesome adaptation method that works'. Sadly, especially for nap-only schedules, there is no free lunch for adaptation, and it is simply necessary to go through the sleep deprivation during the adaptation so that the body can invoke sleep compression.<p>
<p>The adaptation to Uberman is a strenuous and difficult one which is heavily misunderstood. For people without napping experience, the first few days of naps will consist only of light sleep or small amounts of SWS until the REM rebound, which happens on around day 3-5. After this point, the SWS pressure will build until a very dangerous SWS rebound hits on day 7 or 8 of the schedule. The SWS rebound is the hardest part of the adaptation for most dedicated polyphasers and usually results in a SWS crash that wrecks the adaptation. If the crash is avoided, subsequent crashes must also be avoided every 2-3 days until the point of equilibrium between SWS and REM pressures is reached and the schedule smooths itself out. For many people this can take weeks to achieve and some are not properly feeling adapted until they have lived on the schedule for as long as 6 weeks.</p>
<p>It is important to understand that willpower alone is not sufficient to adapt to this schedule. Despite the confidence of many people, will is a finite resource and <strong>once SWS deprivation hits, no amount of willpower will save you.</strong> Electronic devices can be disabled or even ignored - it has been observed in the past that people experiencing an SWS rebound can be completely immune to any and all forms of alarm, including noise-based alarms, flashing lights, loud high-wind fans and even repeated electric shocks from a Pavlok. It is consequently highly recommended (if not necessary) to have a second person supervising you and making sure you are awake at all times, because the advantage of human supervision is that this is a non-issue (as long as the second person is there to keep eye on you). This approach to combatting the SWS deprivation has been used by many  of the known successful Uberman adapters, including both Puredoxyk (woken by Psuke) and the YouTuber aeia (woken by her twin sister). Unfortunately, without a human supervisor, you basically stand no chance at all of adapting to the schedule.</p>
<h3>Delaying the SWS rebound</h3>
<p>It is possible to delay the SWS rebound by a small number of days by adding intermediary naps at SWS-favourable times during the earlier parts of adaptation. Steve Pavlina notably used this method during his approach without realising, as he added an extra nap at 3am between his 1am and 5am naps from days 3 to 8, giving extra SWS time that delayed his SWS rebound until day 12. I have also had personal experiences with this approach, delaying the first SWS rebound until day 9 by adding extra naps earlier on. Unfortunately I don't really advise trying this method, because getting past the SWS rebounds is an important part of the adaptation and you are just delaying the adaptation process by putting it off. (The rebounds will come eventually anyway, regardless of what you do, so you may as well just try to push through them with help of your supervisor.)</p>
<h3>Gradual adaptation</h3>
<p>Some people advocate a gradual approach in which one first adapts to easier schedules before attempting Uberman. While this concept is not necessarily a bad idea in theory, it will significantly drag out the adaptation time while providing only minimal difficulty reduction to the final Uberman attempt, making this sort of approach questionable. For some people though, this could be the difference between success and failure on the schedule.</p>
<p>Here are some possible transitional schedules you could try if you want to take a stab at a gradual adaptation:</p>
<h4>Dual Core 4 (4 hrs 20 mins) and Everyman 5 (3 hrs 10 mins)</h4>
<p><a href="https://napchart.com/qtny6"><img src="https://ncimg.tinytimrob.com/qtny6" height=300 /></a> <a href="https://napchart.com/coamr"><img src="https://ncimg.tinytimrob.com/coamr" height=300 /></a></p>
<p><strong>Adaptation difficulty:</strong> HARD (DC4) / VERY HARD (E5)</p>
<p>These experimental transitional schedules are altered versions of Dual Core 3 and Everyman 4 respectively which have one extra nap added. After adding the extra nap, it is possible to align the cores and naps in a way which matches the rhythm of Uberman, creating the transitional schedules DC4 and E5. This essentially results in Uberman-style schedules where either 1 or 2 naps end up being replaced with cores. In theory, transitioning from these schedules towards Uberman (usually DC4 -> E5 -> U6) will help to train the rhythm and the 'sleepy times' (i.e. when you should feel sleepy) in a less painful way, so that when you start the Uberman schedule you already have these things programmed. It should be pointed out though that the sleep cycles will still have to repartition and compress with each transition, so this is a very slow adaptation approach which can drag out the attempt to over 3 months for the sake of a marginally easier time later on. Whether this is worth the time required is debatable.</p>
<p>Further information about the basics behind Everyman and Dual Core schedules can be found on the relevant scheduling pages.</p>
<h3>Other routes to adaptation</h3>
<p>Other commonly attempted routes to adaptation on Uberman include an 'exaptation' (24-36hrs of no sleep, to more quickly increase sleep pressure and sleep compression) and/or a 'naptation' (napping every 2h, instead of every 4h, to 'learn' napping skills). If you are interested in either of these approaches, they are covered in detail in the adaptation section of this guide.</p>
<h2>Scheduling Variations</h2>
<p>An equidistant six-nap version of Uberman is not the only version which is possible. Here are some alternatives.</p>
<h3>Uberman 8 (2 hrs 40 mins)</h3>
<p><a href="https://napchart.com/75b9t"><img src="https://ncimg.tinytimrob.com/75b9t" height=300 /></a></p>
<p><strong>Adaptation difficulty:</strong> INSANELY HARD</p>
<p><strong>Also known as:</strong> U8</p>
<p>Uberman 8 is a variation of Uberman which has 8 naps instead of 6. It has been proposed in the past by Polyphasic Society. So far there are no reports of success on this schedule, but in theory it might be more sustainable than regular Uberman because of the extra sleep time. (For those with higher sleep needs, the extra 40 minutes might be the difference between make or break on the schedule.) Unfortunately it suffers from the problem of being even more impractical than regular Uberman because the wake time between naps is only 2h40 which is just about too short to be able to viably do anything with. Consequently I don't recommend this schedule.</p>
<h3>Non Equidistant Uberman (2 hrs)</h3>
<p><a href="https://napchart.com/zy2r6"><img src="https://ncimg.tinytimrob.com/zy2r6" height=300 /></a></p>
<p><strong>Adaptation difficulty:</strong> INSANELY HARD</p>
<p>This is another variation which I've sometimes seen suggested. More of the naps are placed at night, where SWS and REM pressure typically tends to be greater. For the sake of completeness I figured I should include this one. Sadly, due to the difficulty staying awake 5h40 on Uberman schedules, I can't recommend this one and it's probably best avoided. I haven't heard of anybody successfully adapting to it either.</p>